services:
  go-event-analyser:
    container_name: go-event-analyser
    image: forgejoe.makiyama.dev.br/makiyama-dev/go-event-analyser:latest
    restart: always
    ports:
      - 1001:3333
    env_file: ".env"
    # injeta o .env local no container
    volumes:
      - ./.env:/usr/src/app/.env  
    depends_on:
      - db
    networks:
      - go-event-analyser

  db:
    container_name: go-event-postgres
    image: postgres:latest
    restart: always
    shm_size: 128mb
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - ./postgres:/var/lib/postgresql # for PRD
    env_file: ".env"
    networks:
      - go-event-analyser

  adminer:
    container_name: go-event-adminer
    image: adminer
    restart: always
    ports:
      - 5433:8080
    networks:
      - go-event-analyser

networks:
  go-event-analyser:
    name: go-event-analyser-net
    external: false
