services:
  go-event-analyser:
    container_name: go-event-analyser-stg
    build: .
    restart: always
    ports:
      - 1002:3333
    env_file: ".env"
    depends_on:
      - db
    networks:
      - go-event-analyser

  db:
    container_name: go-event-postgres-stg
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      #- ./postgres:/var/lib/postgresql # for PRD
    ports:
      - 5442:5432 # HOST_PORT:CONTAINER_PORT
    env_file: ".env"
    networks:
      - go-event-analyser

  adminer:
    container_name: go-event-adminer-stg
    image: adminer
    restart: always
    ports:
      - 5433:8080
    networks:
      - go-event-analyser

networks:
  go-event-analyser:
    name: go-event-analyser-net-stg
    external: false
